import { DataSource } from "@/lib/types/harvester";

export const DEMO_DATA_SOURCES: DataSource[] = [
  {
    id: "src-user-paste",
    name: "User Pasted Listing Checks",
    type: "user_paste",
    permissionStatus: "user_submitted",
    riskLevel: "low",
    enabled: true,
    notes: "Direct unstructured text pasted by active users checking deals",
  },
  {
    id: "src-partner-csv",
    name: "Dhaka Housing Partner Portal",
    type: "partner_csv",
    permissionStatus: "partner_allowed",
    riskLevel: "low",
    enabled: true,
    refreshFrequencyHours: 24,
    notes: "Bulk listings uploaded by registered local agencies via CSV format",
  },
  {
    id: "src-partner-sheet",
    name: "BasaBondhu Main Google Sheet",
    type: "google_sheet",
    permissionStatus: "partner_allowed",
    riskLevel: "low",
    enabled: true,
    refreshFrequencyHours: 12,
    notes: "Shared spreadsheet for broker data normalization and manual review",
  },
  {
    id: "src-agency-public",
    name: "Dhaka Agency Public Feeds",
    type: "agency_website",
    permissionStatus: "public_allowed",
    riskLevel: "medium",
    enabled: true,
    refreshFrequencyHours: 6,
    notes: "Public rental directories from verified Dhaka real-estate agents",
  },
  {
    id: "src-facebook-paste",
    name: "Dhaka Rent Facebook Groups",
    type: "public_directory",
    permissionStatus: "public_allowed",
    riskLevel: "high",
    enabled: false,
    notes: "Crawl/ingest pipelines for Facebook group rental announcements",
  },
  {
    id: "src-cached-crawl",
    name: "Crawl4AI Local Archive Cache",
    type: "cached_snapshot",
    permissionStatus: "demo_snapshot",
    riskLevel: "low",
    enabled: true,
    notes: "Pre-rendered markdown outputs from Crawl4AI agency crawler",
  },
];
