import { HarvestedListing } from "@/lib/types/harvester";

export const DEMO_HARVESTED_LISTINGS: HarvestedListing[] = [
  {
    id: "hlst-demo-1",
    sourceId: "src-user-paste",
    rawDocumentId: "rdoc-demo-1",
    title: "Banasree 3-Bed Family Flat ৳25,000",
    area: "Banasree",
    city: "Dhaka",
    rent: 25000,
    bedrooms: 3,
    bathrooms: 3,
    sizeSqft: 1350,
    tenantPreference: "family",
    familyAllowed: true,
    bachelorAllowed: false,
    femaleFriendly: false,
    studentFriendly: false,
    advanceMonths: 2,
    serviceCharge: 3000,
    serviceChargeKnown: true,
    brokerFee: 0,
    brokerFeeKnown: true,
    gasType: "line",
    lift: true,
    generator: true,
    utilityClarity: "clear",
    waterloggingRisk: "high",
    listingTrust: "high",
    freshnessStatus: "fresh",
    status: "active",
    goodPoints: ["Gas line connection", "Lift and Generator backup", "No broker fee"],
    redFlags: ["High waterlogging risk during monsoon in Banasree"],
    missingFields: [],
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "hlst-demo-2",
    sourceId: "src-facebook-paste",
    rawDocumentId: "rdoc-demo-2",
    title: "Dhanmondi 2-Bed Bachelor Flat ৳32,000",
    area: "Dhanmondi",
    city: "Dhaka",
    rent: 32000,
    bedrooms: 2,
    bathrooms: 2,
    sizeSqft: 1100,
    tenantPreference: "bachelor",
    familyAllowed: true,
    bachelorAllowed: true,
    femaleFriendly: true,
    studentFriendly: true,
    advanceMonths: 1,
    serviceCharge: 4500,
    serviceChargeKnown: true,
    brokerFee: 0,
    brokerFeeKnown: true,
    gasType: "line",
    lift: true,
    generator: true,
    utilityClarity: "clear",
    waterloggingRisk: "low",
    listingTrust: "high",
    freshnessStatus: "fresh",
    status: "active",
    goodPoints: ["Bachelor friendly in central location", "1 month advance", "Gas line", "Generator backup"],
    redFlags: ["Higher rent for 2 bedrooms"],
    missingFields: [],
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
];
